-- APEX CRUSHER — PostgreSQL schema
-- Safe to run multiple times: all statements use IF NOT EXISTS.
-- Deploy via: psql $DATABASE_URL -f scripts/setup_db.sql

-- ── market_data ───────────────────────────────────────────────────────────────
-- Real-time and historical NBBO snapshots for underlying equities.

CREATE TABLE IF NOT EXISTS market_data (
    id          SERIAL          PRIMARY KEY,
    symbol      VARCHAR(10)     NOT NULL,
    timestamp   TIMESTAMPTZ     NOT NULL,
    price       DECIMAL(10, 2),
    volume      BIGINT,
    bid         DECIMAL(10, 2),
    ask         DECIMAL(10, 2)
);

CREATE INDEX IF NOT EXISTS idx_market_data_symbol_ts
    ON market_data (symbol, timestamp DESC);

-- ── options_data ──────────────────────────────────────────────────────────────
-- Point-in-time options chain snapshots (bid/ask/OI/IV per contract).

CREATE TABLE IF NOT EXISTS options_data (
    id             SERIAL          PRIMARY KEY,
    symbol         VARCHAR(10)     NOT NULL,
    strike         DECIMAL(10, 2)  NOT NULL,
    expiry         DATE            NOT NULL,
    option_type    VARCHAR(4)      NOT NULL CHECK (option_type IN ('call', 'put')),
    bid            DECIMAL(10, 2),
    ask            DECIMAL(10, 2),
    volume         INT,
    open_interest  INT,
    iv             DECIMAL(8, 5),
    timestamp      TIMESTAMPTZ     NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_options_data_symbol_expiry
    ON options_data (symbol, expiry);

-- ── calculated_greeks ─────────────────────────────────────────────────────────
-- Black-Scholes Greeks computed by greeks_engine for a specific options_data row.

CREATE TABLE IF NOT EXISTS calculated_greeks (
    id                SERIAL          PRIMARY KEY,
    option_id         INT             NOT NULL REFERENCES options_data (id) ON DELETE CASCADE,
    delta             DECIMAL(8, 5),
    gamma             DECIMAL(8, 5),
    vega              DECIMAL(8, 5),
    theta             DECIMAL(8, 5),
    rho               DECIMAL(8, 5),
    underlying_price  DECIMAL(10, 2),
    timestamp         TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_greeks_option_id
    ON calculated_greeks (option_id);

-- ── signals ───────────────────────────────────────────────────────────────────
-- Trading signals generated by strategy logic, before order placement.

CREATE TABLE IF NOT EXISTS signals (
    id             SERIAL          PRIMARY KEY,
    symbol         VARCHAR(10)     NOT NULL,
    signal_type    VARCHAR(30)     NOT NULL,
    direction      VARCHAR(4)      NOT NULL CHECK (direction IN ('long', 'short')),
    strength       DECIMAL(4, 3),
    strategy_name  VARCHAR(50),
    metadata       JSONB,
    created_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    acted_on       BOOLEAN         NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_signals_acted_on
    ON signals (acted_on);

CREATE INDEX IF NOT EXISTS idx_signals_created_at
    ON signals (created_at DESC);

-- ── trades ────────────────────────────────────────────────────────────────────
-- Paper trade lifecycle: entry, optional exit, PnL.

CREATE TABLE IF NOT EXISTS trades (
    id            SERIAL          PRIMARY KEY,
    symbol        VARCHAR(10)     NOT NULL,
    strike        DECIMAL(10, 2),
    expiry        DATE,
    option_type   VARCHAR(4)      CHECK (option_type IN ('call', 'put')),
    action        VARCHAR(4)      NOT NULL CHECK (action IN ('buy', 'sell')),
    quantity      INT             NOT NULL,
    entry_price   DECIMAL(10, 2)  NOT NULL,
    exit_price    DECIMAL(10, 2),
    pnl           DECIMAL(10, 2),
    strategy      VARCHAR(50),
    status        VARCHAR(10)     NOT NULL DEFAULT 'open'
                                  CHECK (status IN ('open', 'closed', 'cancelled')),
    opened_at     TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    closed_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_trades_status
    ON trades (status);

CREATE INDEX IF NOT EXISTS idx_trades_symbol
    ON trades (symbol, opened_at DESC);
